// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ReheeCmfPackageTest.Data.Instance
{
    public partial class ApplicationDbContextModel
    {
        partial void Initialize()
        {
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaimstring = IdentityRoleClaimstringEntityType.Create(this);
            var identityUserClaimstring = IdentityUserClaimstringEntityType.Create(this);
            var identityUserLoginstring = IdentityUserLoginstringEntityType.Create(this);
            var identityUserRolestring = IdentityUserRolestringEntityType.Create(this);
            var identityUserTokenstring = IdentityUserTokenstringEntityType.Create(this);
            var permisionlong = PermisionlongEntityType.Create(this);
            var healthCheck = HealthCheckEntityType.Create(this);
            var roleBasedPermission = RoleBasedPermissionEntityType.Create(this);
            var myUser = MyUserEntityType.Create(this);
            var entity1 = Entity1EntityType.Create(this);
            var entityInput = EntityInputEntityType.Create(this);

            IdentityRoleClaimstringEntityType.CreateForeignKey1(identityRoleClaimstring, identityRole);
            IdentityUserClaimstringEntityType.CreateForeignKey1(identityUserClaimstring, myUser);
            IdentityUserLoginstringEntityType.CreateForeignKey1(identityUserLoginstring, myUser);
            IdentityUserRolestringEntityType.CreateForeignKey1(identityUserRolestring, identityRole);
            IdentityUserRolestringEntityType.CreateForeignKey2(identityUserRolestring, myUser);
            IdentityUserTokenstringEntityType.CreateForeignKey1(identityUserTokenstring, myUser);

            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimstringEntityType.CreateAnnotations(identityRoleClaimstring);
            IdentityUserClaimstringEntityType.CreateAnnotations(identityUserClaimstring);
            IdentityUserLoginstringEntityType.CreateAnnotations(identityUserLoginstring);
            IdentityUserRolestringEntityType.CreateAnnotations(identityUserRolestring);
            IdentityUserTokenstringEntityType.CreateAnnotations(identityUserTokenstring);
            PermisionlongEntityType.CreateAnnotations(permisionlong);
            HealthCheckEntityType.CreateAnnotations(healthCheck);
            RoleBasedPermissionEntityType.CreateAnnotations(roleBasedPermission);
            MyUserEntityType.CreateAnnotations(myUser);
            Entity1EntityType.CreateAnnotations(entity1);
            EntityInputEntityType.CreateAnnotations(entityInput);

            AddAnnotation("ProductVersion", "6.0.3");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
