name: .NET

on:
  push:
    branches: [ 0_0_1 ]
  pull_request:
    branches: [ 0_0_1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: LS
      run: tree
    - name: Publish .Net Core Project
      run: dotnet publish ReheeCmfPackageTest/ReheeCmfPackageTest.csproj -c Release -o release --nologo
