name: .NET

on:
  push:
    branches: [ 0_0_1 ]
  pull_request:
    branches: [ 0_0_1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Publish .Net Core Project
      run: dotnet publish ReheeCmfPackageTest/ReheeCmfPackageTest.csproj -c Release -o release --nologo
    - name: Build Container image
      run: docker build . --file Dockerfile --tag reheecmfpackagetest
    - name: Push image to docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/reheecmf_package_test:latest
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH: display
        FOLDER: release
